### 01 - Teste de gravidez
Escreva uma célula com controle de fluxos que tem como premissa a existência das seguintes variáveis:

- ```sexo``` como ```str``` indicando os valores '**M**' para masculino e '**F**' para feminino  
- ```beta_hcg``` que indica a quantidade do beta-HCG no sangue em mUI/mL.

A sua tarefa é escrever um código que imprima como resultado "indivíduo do sexo masculino" quando sexo = 'M', caso sexo = 'F', se o valor de beta-HCG for maior que 5, retorne "Positivo" indicando que a paciente está grávida, e retorne "Negativo" caso contrário.

Não mexa nos valores da variável ```sexo``` nem em ```beta_hcg```, e escreva um código que funcione para quaisquer valores possíveis de ambos: ```sexo``` = '**M**' ou '**F**' e ```beta_hcg``` assumindo valores inteiros positivos.

In [1]:
sexo = 'M'
beta_hcg = 0


# seu código vem abaixo desta linha

if sexo == 'M':
    print('masculino')
elif sexo == 'F':
    print('feminino')
else:
    print('erro no sexo')
    
if beta_hcg > 5 :
    print('positivo - paciente est´grávida.')
else:
    print('negativo - paciente não está grávida.')
    



masculino
negativo - paciente não está grávida.


### 02 - Renomeando variáveis

Vamos ver adiante que uma forma de renomear variáveis de um conjunto de dados é através de dicionários - o dicionário deve conter como chave o nome original, associando a cada chave um único valor (tipo *str*) que contenha o nome novo.

A sua tarefa é escrever um dicionário que possa ser utilizado para traduzir as variáveis ```name``` (nome), ```age``` (idade) e ```income``` (renda). Ou seja, esse dicionário deve relacionar as chaves *name, age* e *income* às suas respectivas traduções.

In [2]:
dic_renomeacao ={'name': 'nome', 'age': 'idade', 'income': 'renda'}
dic_renomeacao

{'name': 'nome', 'age': 'idade', 'income': 'renda'}

fim tarefa 2

### 03 - É divisível?
A sua tarefa é escrever um código que indique se um número ```N``` é divisível por um número P. Escreva um programa que faça essa verificação para quaisquer combinações de ```N``` e ```M``` e devolva uma mensagem indicativa no output.

In [3]:
N = 42
M = 7

#Seu código
resultado = 0
resultado = N%M

if resultado == 0:
    print('numero divisivel.')
else:
    print('numero nao dovosivel')
    
resultado2 = 0
N = 0
M = 0
N = int(input('digite o primeiro numero:'))

print(('\n voce digitou ') + str(N))
print("-----------------")
M = int(input('digite o segundo numero:'))
print("------------")
print(('\n voce digitou ') + str(M))
resultado2 = N%M

if resultado2 == 0:
    print('--------------')
    print('\n numeros operacao 2 divisiveis.')
else:
    print('------------')
    print('\n numeros operacao 2 nao sao divisiveis.')
    



numero divisivel.
digite o primeiro numero:33

 voce digitou 33
-----------------
digite o segundo numero:5
------------

 voce digitou 5
------------

 numeros operacao 2 nao sao divisiveis.


fim tarefa 3

### 04 - Números primos
> Um número **N** é primo se e somente se é divisível por 1, -1, por **N** e por -**N**.  

Escreva um script que verifica se ```N``` é um número primo, verificando se ```N``` é divisível por todos os números de ```1``` a ```N-1```. Você vai precisar usar alguma ferramenta de *loop* que você aprendeu para isto. No final, devolva uma mensagem no output indicando se o número é primo ou não.

In [14]:
N = 47
condicao = 0

# seu código abaixo


In [15]:
N = 47
condicao = False  # Inicializamos condicao como False (assumindo que é primo até prova contrária)

# seu código abaixo
divisor = 2

while (divisor < N):
    if N % divisor == 0:
        condicao = True  # Se encontrar um divisor, a condição muda para True (não é primo)
        break  # Podemos sair do loop assim que encontramos um divisor
    divisor += 1  # Incrementamos o divisor para verificar o próximo número

if condicao == False:
    print(f'{N} é um número primo')
else:
    print(f'{N} não é um número primo')

print(f'O número {N} foi testado')

47 é um número primo
O número 47 foi testado


fim tarefa 4

### 05 - Desafio
O algorítmo do exercício anterior não é o mais eficiente. O que você pode fazer para deixá-lo mais eficiente? Ou seja, executar menos comparações, portanto consumir menos tempo.
1. Será que precisamos correr o loop até o final sempre?
2. Será que precisamos mesmo verificar **todos** os números?
3. Será que precisamos ir até N-1?

Essas perguntas levam ao tipo de pensamento voltado a deixar um algoritmo mais eficiente. Veja se você consegue melhorar o seu.

resposta: segundo pesquisa


05 - Desafio¶

O algorítmo do exercício anterior não é o mais eficiente. O que você pode fazer para deixá-lo mais eficiente? Ou seja, executar menos comparações, portanto consumir menos tempo.

Será que precisamos correr o loop até o final sempre?

Será que precisamos mesmo verificar todos os números?

Será que precisamos ir até N-1?

Essas perguntas levam ao tipo de pensamento voltado a deixar um algoritmo mais eficiente. Veja se você consegue melhorar o seu.



R: A função lambda seria a resposta para tornar mais eficiente?

1. me diga se estou certo.

2, me dê um código com esta função tornando o algoritmo mais eficiente.



Olá! Essa é uma ótima reflexão sobre a eficiência do algoritmo de verificação de números primos!

Sobre a sua pergunta:

Não, você não está certo ao afirmar que uma função lambda seria a resposta direta para tornar o algoritmo mais eficiente neste caso. Funções lambda em Python são funções pequenas e anônimas, úteis para criar funções de uso único, geralmente como argumentos para outras funções (como map, filter, sorted). Elas não inherentemente tornam um algoritmo de verificação de primos mais rápido. A eficiência aqui está relacionada à lógica de como você busca os divisores, não na forma como a função é definida.

A chave para tornar o algoritmo mais eficiente reside em otimizar o intervalo de números que você precisa verificar como possíveis divisores.

Pensando na Eficiência:

Não precisamos correr o loop até o final sempre: Se encontrarmos um divisor de N (além de 1 e ele mesmo), já sabemos que N não é primo e podemos parar a verificação imediatamente.
Não precisamos verificar todos os números: Podemos otimizar o intervalo de busca por divisores.
Não precisamos ir até N-1: Um ponto crucial é que se um número N tem um divisor maior que  
N

​
 , ele também deve ter um divisor menor que  
N

​
 . Por exemplo, se N=100, e um divisor é 10 (que é  
100

​
 ), se houvesse um divisor maior, digamos 20, então 100/20=5 também seria um divisor, e 5 é menor que  
100

​
 . Isso significa que precisamos verificar divisores apenas até a raiz quadrada de N.
Código Mais Eficiente:

Aqui está uma versão mais eficiente do algoritmo para verificar se um número é primo:

In [16]:
N = 98

# seu código aqui


import math

def verificar_primo_eficiente(n):
    """
    Verifica se um número N é primo de forma mais eficiente.

    Args:
        n: Um número inteiro a ser verificado.

    Returns:
        True se N for primo, False caso contrário.
    """
    if  <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

# Exemplos de uso:
numero_para_verificar = 47
if verificar_primo_eficiente(numero_para_verificar):
    print(f"{numero_para_verificar} é um número primo")
else:
    print(f"{numero_para_verificar} não é um número primo")

numero_para_verificar = 1000003
if verificar_primo_eficiente(numero_para_verificar):
    print(f"{numero_para_verificar} é um número primo")
else:
    print(f"{numero_para_verificar} não é um número primo")



47 é um número primo
1000003 é um número primo


Resposta sem uso de função

In [17]:
import math

N = 98
eh_primo = True  # Assumimos que o número é primo até prova contrária

if N <= 1:
    eh_primo = False
elif N <= 3:
    eh_primo = True
elif N % 2 == 0 or N % 3 == 0:
    eh_primo = False
else:
    i = 5
    while i * i <= N:
        if N % i == 0 or N % (i + 2) == 0:
            eh_primo = False
            break  # Não precisamos continuar verificando se encontramos um divisor
        i += 6

if eh_primo:
    print(f"{N} é um número primo")
else:
    print(f"{N} não é um número primo")

98 não é um número primo


fim tarefa 5

# 06 - Peso ideal 1
 
O IMC (índice de massa corpórea) é um indicador de saúde mais bem aceito que o peso. Ele é calculado como:

𝐼𝑀𝐶=𝑝𝑒𝑠𝑜𝑎𝑙𝑡𝑢𝑟𝑎2
 

Segundo a OMS, valores normais são entre 18.5 e 24.9.

Sua tarefa é encontrar o ponto médio dessa faixa.

In [6]:
imc_ideal = 
imc_ideal

SyntaxError: invalid syntax (2468708578.py, line 1)

resolvendo tarefa 6

solução tarefa 6 - 1

In [38]:
import math

imc = 0
peso = 100.0
altura = 1.77

imc = peso / (altura ** 2)  # Correção: use ** para potência
   
imc_ideal = False

if ((imc > 18.5) and (imc < 24.9)):
    imc_ideal = True
    print('imc ideal.')
else:
    print('imc não ideal.')

    





imc não ideal.


solução tarefa 6 melhorada

In [55]:
import math

imc = 0
peso = 71.5 #algo entre 71.50 e 72 ideal
altura = 1.70  # Use ponto como separador decimal

imc = peso / (altura ** 2)  # Correção: use ** para potência

imc_ideal = False  # Use False (booleano) em vez de F

if 18.5 <= imc <= 24.9:  # Sintaxe mais concisa e correta para o intervalo
    imc_ideal = True  # Use True (booleano) em vez de V
    print('imc de ' + str(round(imc, 3)) + ' ideal.')
else:
    print('imc de ' + str(round(imc, 3)) + ' não ideal.')

imc de 24.74 ideal.


### 07 - Peso ideal 2
Recebendo um valor de altura, encontre o peso '*ideal*' dessa pessoa, que fornece o IMC encontrado acima

In [ ]:
altura = 1.70

# Seu código
peso_ideal = 
peso_ideal

resolvendo tarefa 7
se o imc é peso sobre altura ao quadrado
o peso seria altura ao quadrado vezes imc




In [56]:
altura = 1.70

#peso?
#imc ideal 18.5 <= imc <= 24.9
# peso ideal 71.5 <= imc <= 72.0

# Seu código

#peso_ideal = 
#peso_ideal


import math

imc = 24.74 
peso = 0.0
altura = 1.70  # Use ponto como separador decimal

peso = imc * (altura ** 2)  # Correção: use ** para potência

peso_ideal = False  # Use False (booleano) em vez de F

if 71.5 <= peso <= 72.0:  # Sintaxe mais concisa e correta para o intervalo
    peso_ideal = True  # Use True (booleano) em vez de V
    print('peso de ' + str(round(peso, 3)) + ' ideal.')
else:
    print('peso de ' + str(round(peso, 3)) + ' não ideal.')

peso de 71.499 não ideal.


tarefa 7 melhorada com ia

TAREFA 7

Análise sobre erros e acertos:

Vamos analisar o seu código e o seu raciocínio para essa tarefa:

O que você ACERTOU:

Cálculo do Peso: Você utilizou a fórmula correta para calcular o peso a partir do IMC e da altura: peso = imc * (altura ** 2).
Uso da Altura: Você definiu corretamente a altura como 1.70.
Conceito de Faixa Ideal: Você entendeu que existe uma faixa para o peso ideal, correspondente à faixa de IMC ideal.
Estrutura Condicional: Você utilizou um if/else para verificar se o peso calculado está dentro da faixa ideal que você definiu.
O que você ERROU e onde houve INCONSISTÊNCIAS:

Definição do imc: Você definiu imc = 24.74 diretamente no código. A tarefa pedia para encontrar o peso ideal dado uma altura, utilizando o IMC ideal. O IMC não deveria ser um valor fixo no seu cálculo do peso ideal. O objetivo era usar a faixa de IMC ideal para determinar a faixa do peso ideal.
Faixa de Peso Ideal Manual: Você definiu manualmente a faixa de peso ideal como 71.5 <= peso <= 72.0. Essa faixa parece ser um resultado específico para um determinado IMC, mas não demonstra o processo de calcular essa faixa a partir do IMC ideal (18.5 a 24.9).
Variável peso_ideal como Booleano: Você utilizou a variável peso_ideal como um booleano (True ou False) para indicar se o peso calculado com um IMC fixo estava dentro da sua faixa manual. O objetivo da tarefa era calcular o valor ou a faixa do peso ideal, não apenas verificar se um peso específico é ideal.
Comentários Incorretos: Seus comentários # peso ideal 71.5 <= imc <= 72.0 estão incorretos. A faixa se refere ao peso, não ao IMC.
Como a Tarefa Deveria Ter Sido Abordada (similar à resposta anterior):

O objetivo era usar a faixa de IMC ideal (18.5 a 24.9) para calcular a faixa do peso ideal para a altura dada.

Para encontrar o peso "ideal" de uma pessoa com uma determinada altura, utilizando a faixa de IMC ideal (18.5 a 24.9), precisamos fazer alguns cálculos. A fórmula do IMC é:

IMC= 
altura (m) 
2
 
peso (kg)
​
 

Para encontrar o peso, podemos rearranjar essa fórmula:

peso (kg)=IMC×altura (m) 
2
 

Como temos uma faixa de IMC ideal, teremos também uma faixa de peso ideal. Vamos calcular o peso ideal mínimo (com IMC de 18.5) e o peso ideal máximo (com IMC de 24.9) para a altura fornecida de 1.70 metros.

In [58]:
# CODIGO ANALISE DA TAREFA 

altura = 1.70

# Faixa de IMC ideal
imc_minimo_ideal = 18.5
imc_maximo_ideal = 24.9

# Cálculo do peso ideal mínimo
peso_ideal_minimo = imc_minimo_ideal * (altura ** 2)

# Cálculo do peso ideal máximo
peso_ideal_maximo = imc_maximo_ideal * (altura ** 2)

print(f"Para uma altura de {altura} metros, o peso ideal está entre:")
print(f"- Mínimo: {peso_ideal_minimo:.2f} kg")
print(f"- Máximo: {peso_ideal_maximo:.2f} kg")

Para uma altura de 1.7 metros, o peso ideal está entre:
- Mínimo: 53.46 kg
- Máximo: 71.96 kg


fim tarefa 7

### 08 - Peso ideal 3
Dada uma lista contendo as alturas de pacientes, crie uma nova lista que contenha o peso '*ideal*' (que fornece o IMC calculado em **Peso ideal 1**) desses pacientes.

In [ ]:
lista_alturas = [1.95, 2.05, 1.70, 1.65]

lista_peso_ideal = []

# seu código

lista_peso_ideal




resolvendo tarefa 8

In [12]:
lista_alturas = [1.95, 2.05, 1.70, 1.65]

lista_peso_ideal = []

# seu código

# Faixa de IMC ideal
imc_minimo_ideal = 18.5
imc_maximo_ideal = 24.9




#for i in range(len(lista)):

#23	
#def nome (parâmetro):
#bloco de código
#return

def calculo_peso_ideal(altura,imc_max,imc_min):
    peso_ideal_min = 0.0
    peso_ideal_max = 0.0
    

    # Cálculo do peso ideal mínimo
    peso_ideal_min = imc_min * (altura ** 2)

    # Cálculo do peso ideal máximo
    peso_ideal_max = imc_max * (altura ** 2)
    return(peso_ideal_min,peso_ideal_max)




for i in range(len(lista_alturas)):
    peso_ideal = calculo_peso_ideal(lista_alturas(i))
    lista_peso_ideal.append(peso_ideal)
    

    
print(lista_peso_ideal)



#ista_peso_ideal



TypeError: 'list' object is not callable

versão melhorada com ia

Correções aplicadas:

Definição da Função: A função calculo_peso_ideal foi movida para o início do código, antes de ser chamada, garantindo que ela esteja definida quando for utilizada.
Acesso aos Elementos da Lista: A forma de acessar os elementos da lista lista_alturas no loop foi corrigida de lista_alturas(i) para iterar diretamente sobre os elementos da lista (for altura in lista_alturas:), que é uma forma mais idiomática e legível em Python. Se o acesso por índice fosse estritamente necessário, o correto seria lista_alturas[i].
Chamada da Função: A chamada da função calculo_peso_ideal foi corrigida para passar os argumentos corretos: a altura atual (altura), o IMC mínimo (imc_minimo_ideal) e o IMC máximo (imc_maximo_ideal).
Tratamento do Retorno da Função: A função calculo_peso_ideal retorna uma tupla contendo o peso ideal mínimo e máximo. O loop agora recebe essa tupla e a adiciona como um único elemento à lista lista_peso_ideal, conforme a lógica do código original parecia indicar (armazenar a faixa de peso ideal por paciente).
Variáveis de IMC: As variáveis imc_minimo_ideal e imc_maximo_ideal foram mantidas e posicionadas antes do loop para serem utilizadas na chamada da função.
Este código corrigido irá iterar sobre cada altura na lista_alturas, calcular a faixa de peso ideal (mínimo e máximo) para essa altura usando os limites de IMC fornecidos e armazenar essa faixa (como uma tupla) na lista_peso_ideal. Finalmente, ele imprimirá a lista_peso_ideal resultante.

In [10]:
def calculo_peso_ideal(altura, imc_min, imc_max):
  """
  Calcula a faixa de peso ideal (mínimo e máximo) para uma dada altura
  e uma faixa de IMC ideal.

  Args:
    altura (float): A altura do paciente em metros.
    imc_min (float): O valor mínimo da faixa de IMC ideal.
    imc_max (float): O valor máximo da faixa de IMC ideal.

  Returns:
    tuple: Uma tupla contendo o peso ideal mínimo e o peso ideal máximo
            para a altura fornecida, com base na faixa de IMC.
  """
  peso_ideal_min = 0.0
  peso_ideal_max = 0.0

  # Cálculo do peso ideal mínimo (Peso = IMC_min * Altura^2)
  peso_ideal_min = imc_min * (altura ** 2)

  # Cálculo do peso ideal máximo (Peso = IMC_max * Altura^2)
  peso_ideal_max = imc_max * (altura ** 2)

  return (peso_ideal_min, peso_ideal_max)


lista_alturas = [1.95, 2.05, 1.70, 1.65]
lista_peso_ideal = []

# Faixa de IMC ideal
imc_minimo_ideal = 18.5
imc_maximo_ideal = 24.9

# Percorre a lista de alturas para calcular o peso ideal para cada paciente
for altura in lista_alturas:
  # Calcula a faixa de peso ideal (mínimo e máximo) para a altura atual
  peso_ideal_range = calculo_peso_ideal(altura, imc_minimo_ideal, imc_maximo_ideal)
  # Arredonda os valores mínimo e máximo, e formata como string
  peso_ideal_min_arredondado = round(peso_ideal_range[0], 3)
  peso_ideal_max_arredondado = round(peso_ideal_range[1], 3)
  lista_peso_ideal.append(f"Peso Ideal: [{peso_ideal_min_arredondado:.2f} kg - {peso_ideal_max_arredondado:.2f} kg]")

# Imprime a lista contendo as faixas de peso ideal para cada altura
print(lista_peso_ideal)

['Peso Ideal: [70.35 kg - 94.68 kg]', 'Peso Ideal: [77.75 kg - 104.64 kg]', 'Peso Ideal: [53.47 kg - 71.96 kg]', 'Peso Ideal: [50.37 kg - 67.79 kg]']


### 09 - Peso ideal 4
Dada uma lista de tuplas - cada elemento da lista é uma tupla contendo altura e peso de um paciente - crie uma nova lista com o IMC desses pacientes.

In [ ]:
altura_peso = [(1.80, 90), (1.65, 75), (1.91, 70)]

imc = []

# seu código

imc

resolvendo tarefa 9

In [6]:
altura_peso = [(1.80, 90), (1.65, 75), (1.91, 70)]

imc = []

# seu código


def calcula_imc(altura_peso_item):

    imc = altura_peso_item[1] / (altura_peso_item[0] ** 2)

    return(round(imc,3))


for altura_peso_item in altura_peso:

    imc_calculado = calcula_imc(altura_peso_item)
    imc.append(imc_calculado)


print(imc)


[27.778, 27.548, 19.188]


fim tarefa 9 - feita sem ajuda de IA

### 10 - Peso ideal 5
Dada uma lista de **listas** - cada elemento da lista é uma **lista** contendo altura e peso de um paciente, adicione mais um elemento à lista de cada paciente contendo o IMC do paciente. Verifique também se é 'baixo', 'normal' ou 'alto' segundo os padrões da OMS em que normal é entre 18.5 e 24.9.

Reflexão: por que no problema anterior temos que criar uma nova lista, e não podemos adicionar os dados de cada indivíduo à tupla?

In [ ]:
altura_peso = [[1.80, 90], [1.65, 75], [1.91, 70]]

# seu código

altura_peso

resolvendo tarefa 10

In [6]:
altura_peso = [[1.80, 90], [1.65, 75], [1.91, 70]]
# lista para teste: altura_peso = [[1.80, 90], [1.65, 75], [1.91, 70],[1.70,60.0]]
# seu código
imc_ideal = False

def calcula_imc(altura_peso_item):

    imc = altura_peso_item[1] / (altura_peso_item[0] ** 2)

    return(round(imc,3))


for altura_peso_item in altura_peso:

    imc_calculado = calcula_imc(altura_peso_item)
    if  18.5 <= imc_calculado <= 24.9:  # imc ideal
        peso_ideal = True  # Use True (booleano) em vez de V
        altura_peso_item.append(imc_calculado)
        altura_peso_item.append("imc ideal")
    else:
        altura_peso_item.append(imc_calculado)
        altura_peso_item.append("imc nao ideal")


print(altura_peso)


[[1.8, 90, 27.778, 'imc nao ideal'], [1.65, 75, 27.548, 'imc nao ideal'], [1.91, 70, 19.188, 'imc ideal']]


fim codigo tarefa 10 - feito sem ia

#ajuda de ia apenas para compreender a tarefa, não na codificação.

Okay, vamos explicar a tarefa e o código.

Explicação da Tarefa

Você tem uma lista chamada altura_peso. Dentro dessa lista principal, há outras listas menores. Cada uma dessas listas menores representa um paciente e contém dois números: a altura do paciente (em metros) e o peso (em quilogramas).

Sua tarefa é processar cada um desses pacientes (cada lista interna):

Calcular o IMC: Usando a altura e o peso do paciente, você deve calcular o Índice de Massa Corporal (IMC) usando a fórmula: $ \text{IMC} = \frac{\text{peso}}{\text{altura}^2} $
Adicionar o IMC: O valor do IMC calculado deve ser adicionado como um terceiro elemento à lista desse paciente.
Classificar o IMC: Com base no valor do IMC, você deve determinar se a classificação é 'baixo', 'normal' ou 'alto' de acordo com os padrões da OMS:
IMC menor que 18.5: 'baixo'
IMC entre 18.5 e 24.9 (inclusive): 'normal'
IMC maior que 24.9: 'alto'
Adicionar a Classificação: A string correspondente à classificação ('baixo', 'normal' ou 'alto') deve ser adicionada como um quarto elemento à lista desse paciente.
Ao final, a lista altura_peso original deverá estar modificada, com cada lista interna contendo agora 4 elementos: [altura, peso, IMC calculado, classificação].

Código Python para a Tarefa
... não foi usado



PARTE 2 - MINHA RESPOSTA DA REFLEXÃO

Reflexão: por que no problema anterior temos que criar uma nova lista, e não podemos adicionar os dados de cada indivíduo à tupla?

R: Porque na tupla os elementos são não ordenáveis e devem ser do mesmo tipo.

correção da Reflexão na IA:

Resposta à Reflexão:
Se no "problema anterior" os dados de cada indivíduo estavam armazenados em tuplas (por exemplo, (altura, peso)), você não poderia simplesmente usar um método como append() para adicionar o IMC ou a classificação a essa tupla existente. Como as tuplas são imutáveis, a única maneira de ter os dados originais junto com as novas informações (IMC, classificação) seria criar uma nova tupla ou uma nova lista que contivesse todos esses dados. Você não estaria modificando a tupla original, mas sim construindo uma estrutura de dados completamente nova a partir dos dados antigos mais os dados calculados.

Em resumo, a necessidade de criar uma nova lista (ou outra estrutura) no problema anterior provavelmente surgiu porque os dados individuais estavam em um tipo de dado imutável (como uma tupla), enquanto neste problema atual, eles estão em um tipo de dado mutável (uma lista), permitindo modificações in-place.

fim tarefa 10